### ISSUE TITLE
Protocol agnostic socket

### ISSUE THREAD

**Issue by povilasb** [maidsafe/socket-collection#11]
Currently socket-collection exposes separate structures for different protocols: UDP, TCP, etc. All of those sockets implement similar API, but we need a single abstraction that wraps all the protocol implementations to ease it's integration into p2p and Crust.

1. Call this abstraction `Socket`
1. Investigate if `Socket` needs to be a trait or an enum with other sockets as variants.
1. This abstraction should provide the common APIs shared by the sockets it's wrapping.
1. If there's an API in one and not in other then we can mimic that API as NoOp in the other where it lacks and give an appropriate return - e.g., if the return type is a `Result` then an `InvalidOperation` error would do so that the caller does not have to do anything special and can read the doc and branch on the error type if necessary. This will keep the API uniform in this protocol agonostic layer.

**Comment by ustulation** [comment]
Went with enums [as here](https://github.com/maidsafe/socket-collection/pull/28) because with traits we'll require to either hold it as trait object by `Box`ing it (thus heap allocation) or templatising the types in the user code on `Socket` which is quite verbose.
